### ISSUE TITLE
Organising library/bookshelf by domain

### ISSUE THREAD

**Issue by drllau** [TokenEngineeringCommunity/website#2]
![map-domains](https://user-images.githubusercontent.com/14944510/81488973-ca9f0d80-92a2-11ea-8d12-869382001b50.png)

Because token engineering is (at moment) interdisciplinary, organise the dead-tree reading material by knowledge domain. I (tentatively) suggest ordering it:
1. Engineering Ethics
2. Governance
3. Decision science
4. Cryptography
5. Control Theory
6. Systems Engineering
7. Technology 
8. Game Theory

**Comment by burrrata** [comment]
Right now it's just a big list. If you want to re-organize it, however, that would be awesome. Feel free to do so and submit a PR. 

Also, in addition to the categories you mentioned I think we should have a 101 or Getting Started category that has 1-2 simple/easy resources from all the other categories.
