### ISSUE TITLE
Inserting image on getting-started-welcome page

### ISSUE THREAD

**Issue by Jeff-Emmett** [TokenEngineeringCommunity/website#9]
Hey Burrrata,

Just wondering if you'd be able to help with the the destination path for the image I put on the page, and I can fill in the rest once I see how the format works.

Thanks for your help!

**Comment by burrrata** [comment]
Is there a branch or PR or something where I can see what you're trying to do? In general, all images should be in the `static/img/` folder, but how you like to them depends on the context in which you're trying to insert it.
